default_stages: [pre-commit]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-symlinks
    -   id: no-commit-to-branch
        args:
        -   --branch=main
        -   --branch=qa

-   repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile requirements-dev.in
        args: [requirements-dev.in, --quiet, --strip-extras, --resolver=backtracking]
        files: ^requirements-dev\.in$
      - id: pip-compile
        name: pip-compile requirements.in
        args: [requirements.in, --quiet, --strip-extras, --resolver=backtracking]
        files: ^requirements\.in$

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.2
    hooks:
    -   id: sqlfluff-lint
        args:
        -   --dialect=postgres
    -   id: sqlfluff-fix
        args:
        -   --dialect=postgres
        stages:
        -   manual

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
    -   id: black-jupyter

-   repo: local
    hooks:
    -   id: pip-sync
        name: pip-sync
        entry: pip-sync
        language: system
        args: [requirements.txt, requirements-dev.txt]
        files: ^requirements(-dev)\.txt$
        pass_filenames: false
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        require_serial: true
        args:
        -   --fail-under=7
    -   id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        language: system
        types: [python]
        require_serial: true
    # -   id: build-docs
    #     name: build sphinx docs
    #     language: system
    #     entry: make doc
    #     stages:
    #     -   pre-push
    -   id:  tag-issue
        name: check tag issue in commit message
        language: pygrep
        entry: "#[0-9]+"
        args:
        -   --negate
        stages:
        -   commit-msg