name: New release
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
  if_base_release:
    needs: if_merged
    if: startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR's base branch is ${{ github.head_ref }}"
  get_versions:
    needs: if_base_release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_current_version.outputs.substring }}
      next_version: ${{ steps.get_next_version.outputs.version }}
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: get_current_version
        with:
          value: ${{ github.head_ref }}
          index_of_str: "releases/"
      - id: get_next_version
        run: echo "version=$(echo ${{ steps.get_current_version.outputs.substring }} | awk -F. -v OFS=. '{$(NF-1) += 1; $NF = 0; print}')" >> $GITHUB_OUTPUT
  draft_release_notes:
    needs: get_versions
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh release create 'v${{ needs.get_versions.outputs.version }}' \
          --repo tahaislam/airflow-mate --target main --draft --generate-notes --latest \
          --title 'VFH ${{ needs.get_versions.outputs.version }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update_version:
    needs: get_versions
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update pyproject.toml
        run: |
          git config --global user.email "github-actions@toronto.com"
          git config --global user.name "github-actions"
          git checkout -b releases/${{ needs.get_versions.outputs.next_version }} main
          sed -i '/^\[project\]$/,/^\[/ s/^version = .*$/version = "${{ needs.get_versions.outputs.next_version }}"/' pyproject.toml
          sed -i '/^\[project\]$/,/^\[/ s/^latest_release_tag = .*$/latest_release_tag = "${{ needs.get_versions.outputs.version }}"/' pyproject.toml
          git add pyproject.toml
          git commit -m "update project's version to ${{ needs.get_versions.outputs.next_version }}"
          git push --set-upstream origin releases/${{ needs.get_versions.outputs.next_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_milestone:
    needs: [get_versions, update_version]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: ${{ needs.get_versions.outputs.next_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  create_pr_for_new_release:
    needs: [get_versions, create_milestone]
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh pr create --base main --head releases/${{ needs.get_versions.outputs.next_version }} \
          --milestone "v${{ needs.get_versions.outputs.next_version }}" \
          --title 'Update the version number for the new release' --repo tahaislam/airflow-mate \
          --body 'Please, update the version number (`version`) in docs/source/conf.py to an appropriate value \
          and `latest_release_tag` to ${{ needs.get_versions.outputs.version }}. Remember also to create a new milestone for the upcoming release.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
