name: New release
on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo The PR was merged
  if_base_release:
    needs: if_merged
    if: startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
      - run: echo "This PR's base branch is ${{ github.head_ref }}"
  draft_release_notes:
    needs: if_base_release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: get_version
        with:
          value: ${{ github.head_ref }}
          index_of_str: "releases/"
      - run: gh release create 'v${{ VERSION }}' --draft --generate-notes --latest --target main --title 'VFH $VERSION' --repo tahaislam/airflow-mate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.substring }}
  init_new_dev_release:
    needs: if_base_release
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: bhowell2/github-substring-action@1.0.2
        id: get_version
        with:
          value: ${{ github.head_ref }}
          index_of_str: "releases/"
      - run: |
          gh issue create --title 'Update the version number for the new release' --repo tahaislam/airflow-mate \
          --body 'Please, update the version number (`version`) in docs/source/conf.py to an appropriate value \
          and `latest_release_tag` to ${{ VERSION }}. Remember also to create a new milestone for the upcoming release.'
          # --label 'ignore-for-release' --project 'VFH Data Management' \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.substring }}
